[package]
name = "deferred-box"
version = "0.1.3"
description = "Defer the value set after the struct has been initialized"
edition = "2021"
license = "MIT"
repository = "https://github.com/victorteokw/deferred-box"

[dependencies]
